# Generated by Django 5.0.3 on 2024-03-21 07:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_organizationmodel_organization_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('coord_x', models.FloatField(verbose_name='Координаты X')),
                ('coord_y', models.FloatField(verbose_name='Координаты Y')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 3, 21, 14, 23, 24, 119854), null=True, verbose_name='Дата')),
                ('event_admin', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Администратор организации')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationmodel', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
