# Generated by Django 5.0.3 on 2024-03-25 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_eventmodel_event_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 23, 44, 9, 258107), null=True, verbose_name='Дата'),
        ),
    ]
