# Generated by Django 5.0.3 on 2024-03-25 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventmodel_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 23, 49, 19, 635906), null=True, verbose_name='Дата'),
        ),
    ]
