# Generated by Django 5.0.4 on 2024-05-03 10:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventmodel_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='member_count',
            field=models.IntegerField(default=0, verbose_name='Колличество участников'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 17, 54, 27, 498376), null=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('image', models.ImageField(upload_to='event/cover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='изображение')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.eventmodel')),
            ],
        ),
    ]
