# Generated by Django 5.0.4 on 2024-05-15 16:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventmodel_member_count_eventmodel_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 23, 14, 47, 555770), null=True, verbose_name='Дата'),
        ),
    ]
