# Generated by Django 5.0.4 on 2024-05-15 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventmodel_members_alter_eventmodel_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 23, 46, 0, 524860), null=True, verbose_name='Дата'),
        ),
    ]
