# Generated by Django 5.0.3 on 2024-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('descriptions', models.CharField(max_length=255, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Комментарий к событию',
                'verbose_name_plural': 'Комментарии к событиям',
            },
        ),
    ]
