# Generated by Django 5.0.2 on 2024-02-24 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='music/cover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='изображение')),
                ('coord_x', models.IntegerField(default=0, verbose_name='Координаты X')),
                ('coord_y', models.IntegerField(default=0, verbose_name='Координаты Y')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
