# Generated by Django 5.0.2 on 2024-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='coord_x',
            field=models.IntegerField(verbose_name='Координаты X'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='coord_y',
            field=models.IntegerField(verbose_name='Координаты Y'),
        ),
    ]
