# Generated by Django 5.0.2 on 2024-02-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organizationmodel_coord_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='coord_x',
            field=models.FloatField(verbose_name='Координаты X'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='coord_y',
            field=models.FloatField(verbose_name='Координаты Y'),
        ),
    ]
