# Generated by Django 5.0.3 on 2024-03-21 05:54

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organizationmodel_coord_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='organization_admin',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Администратор организации'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='image',
            field=models.ImageField(upload_to='organizatons/cover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='название'),
        ),
    ]
