# Generated by Django 5.0.3 on 2024-05-01 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_organizationmodel_organization_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmodel',
            name='image',
        ),
        migrations.CreateModel(
            name='OrganizationImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('image', models.ImageField(upload_to='organization/cover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='изображение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationmodel')),
            ],
        ),
    ]
