# Generated by Django 5.0.3 on 2024-05-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_organizationmodel_image_organizationimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationimages',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='organization.organizationmodel'),
        ),
    ]
