# Generated by Django 5.0.4 on 2024-05-15 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_organizationimages_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='status',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Статус одобрения'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='organization_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Администратор организации'),
        ),
    ]
